### ISSUE TITLE
Aggregating/de-duping dependency vulnerabilities across projects

### ISSUE THREAD

**Issue by ghost** [SonarSecurityCommunity/dependency-check-sonar-plugin#25]
A lot of my projects use common dependencies between them, but at this time there is no way to aggregate dependencies between projects and they all show up as being unique.

Being able to see how many instances of each unique vulnerable component would make triaging much easier. What would it take to make this happen?

**Comment by stevespringett** [comment]
A SonarQube issue can be assigned to a source file or to a project. The DC plugin assigns issues to the project. There is no way to assign a single issue to multiple projects in SQ or otherwise aggregate them to my knowledge.

Take a look at OWASP Dependency-Track. It is designed specifically for this purpose. Work is underway on a complete rewrite (v3.0), but the 1.x code may still be useful - even in the short term.

https://www.owasp.org/index.php/OWASP_Dependency_Track_Project
https://github.com/stevespringett/dependency-track
https://www.youtube.com/watch?v=3B3VKGwYS2A

**Comment by Reamer** [comment]
Closing this issue, because it's quite old. With Version [1.2.2](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/releases/tag/1.2.2) and above only dependency-check:aggregate is supported.
