### ISSUE TITLE
Seeking New Maintainer

### ISSUE THREAD

**Issue by stevespringett** [SonarSecurityCommunity/dependency-check-sonar-plugin#75]
I’m looking for a new maintainer of the OWASP Dependency-Check SonarQube plugin. I created the plugin in January 2015 and have been maintaining it since, however, I no longer use SonarQube and the project could benefit from someone who does.

I also created the ZAP plugin based on the same code and transferred ownership of that project awhile back. I'm happy to report that project is doing extremely well as a result. My hope is that the same happens for the Dependency-Check SonarQube plugin.

If interested, please respond to this ticket

**Comment by pethers** [comment]
Use sonarqube and like the plugin so hope you find somebody. Limited time but could probably help out making releases and support uppcoming sonarqube versions. Pretty happy with the current feature set.

**Comment by Reamer** [comment]
Hi  @stevespringett 
I am using sonarqube as well. I use the maven plugins sonar and dependency-check and could support multi module support.

I'm interested in supporting, that this project has a version working with latest sonarqube LTS and latest stable version. I'm also interested in PRs #63 and #77.

At the moment I can't support:
 - Working with Gradle, Sonar Cli or Jenkins-Plugin
 - Working with Other languages then Java
In most cases it's because of missing projects

Best Regards
Reamer

**Comment by bradflood** [comment]
Hi @stevespringett  - first, thank you for creating and maintaining this plugin.  It's been very helpful in shedding light on vulnerabilities within client organizations

Regarding the transfer, would you be willing to add @pethers , @Reamer and me as committers?

**Comment by stevespringett** [comment]
@bradflood Invitations sent. @pethers, @Reamer, and yourself should all get invites.

**Comment by stevespringett** [comment]
@teha75, yes, that's a possibility. A move on GitHub is fairly straight-forward but will require the acceptance of the person responsible to maintaining the SonarOpenCommunity organization. Links to the project (including git remote locations) are automatically forwarded when this happens.

**Comment by bradflood** [comment]
is there a reason we would not want to move it to [SonarQube Community](https://github.com/SonarQubeCommunity/)?  I maintained another SonarQube plugin that was in community awhile ago; it seems to be more tightly integrated with their marketplace.  I don't mind shepherding the movement to SonarQube community if that is what the group wants to do

**Comment by stevespringett** [comment]
I think we have majority vote. 

If you go back to my previous objections for not wanting to join the [SonarQube Community](https://github.com/SonarQubeCommunity/), it came down to not wanting to conform to their processes which were very anti-community. For example, not being able to release whenever you want (required a non-objecting voting consensus), and their ability to drop the plugin from the marketplace if SonarSource decided it was competing against a plugin or offering of their own. There was a lot of process for process sake with the majority of SonarQube plugins that were not developed by SonarSource, NOT being part of the official marketplace. Refer to #46 for background info.

If someone wants to take that on, I think it would be valuable to be part of the official community. I never objected to the value of the marketplace, rather what was required to get there and maintain a status there.

If someone does not want to take that on, then perhaps [SonarQube Open Community](https://github.com/SonarOpenCommunity) (as mentioned by @teha75) may be a more suitable destination.

**Comment by bradflood** [comment]
Thanks for the background @stevespringett.   I will initiate a conversation with SonarSource, and if it seems too burdensome, we can fall back and explore the SonarQube Open Community

**Comment by stevespringett** [comment]
One more note. If the location of this project changes, you all may want to ping https://github.com/OWASP/sonarqube . They have a Dockerfile that contains this plugins distribution URL. Maybe do a PR for them as a courtesy :-) and as a way to introduce yourselves and the new project location.

**Comment by VinodAnandan** [comment]
Thanks @stevespringett, The community security plugins (Find-Sec-Bugs, SpotBugs, Mutation Testing, OWASP DepedencyCheck, etc. ) is one of the main reasons for the OWASP SonarQube project.  My plan is to package all of the community plugins and utilize the OWASP SonarQube as a SAST . The plugins will be packaged irrespective of the official Market Place status (https://hub.docker.com/r/owasp/sonarqube/ ).  The OWASP SonarQube project mainly depends upon these opensource plugins, that's why I have decided to work closely with them.

So if you guys are interested we can also consider moving the repository under the OWASP SonarQube project or we can request OWASP for a new project for it.  Also maybe in the future we can consider the Dependency Track integrations as well.

I am also happy to have more volunteers for the OWASP SonarQube project.

**Comment by stevespringett** [comment]
Has any progress been made on finding a new home for this repo?

**Comment by Reamer** [comment]
I would prefer a location with the flexibility of a normal project. Release a new version, when features are ready and so on.
I think a new project under OWASP would be a nice location. How it is possible to add third party tools like TravisCI codacy under OWASP?

**Comment by stevespringett** [comment]
@Reamer I pinged the OWASP GitHub admins to check if this is possible. Will let you know. If not, then perhaps an alternative would be to create a SonarQube Security Plugins org and move it there. Lets find out what OWASP has to say though.

**Comment by stevespringett** [comment]
There has been no response from OWASP github admins. So I have created a new GitHub organization and have invited @Reamer, @bradflood, and @pethers to it. The idea is to have an org which is dedicated to SonarQube security plugins that are not part of the marketplace.

https://github.com/SonarSecurityCommunity

**Comment by stevespringett** [comment]
I plan on moving this repo to https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin on Friday.
